language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - pip install -r test_requirements.txt
  - python setup.py install
script:
  coverage run --source=pip_accel -m nose tests
after_success:
  coveralls
